### ISSUE TITLE
Some module exports may break the build

### ISSUE THREAD

**Issue by Toilal** [ktsn/vue-hot-reload-loader#6]
For some reason, I need to create this dummy module ...

```javascript
require("muicss/lib/sass/mui.scss");
require("./mui-layout.scss");

export default function(){};
```

This is not a Vue component at all, but vue-hot-reload-loader consider it is, and it then throw an exception inside the vue-hot-loader-api.

We should provide a way to ignore some module.

```javascript
require("muicss/lib/sass/mui.scss");
require("./mui-layout.scss");

/* vue-hot-reload-loader: false */
export default function(){};
```

Also, we should think about improving the detection of Vue components to avoid using this comment on every non-component modules. Do you have any idea to enhance Vue component module detection ?

**Comment by ktsn** [comment]
I'm not sure that introducing such annotation comment is a good idea.
Why do you want to use this approach rather than adding include/exclude field in webpack config?

**Comment by Toilal** [comment]
I don't want to end up with a big list of files to exclude in the webpack configuration. But I agree it's not optimal, and it requires configuration on previous loaders to preserve comments... 

Best would be enhance the quality of components detection to make sure it only handle modules exporting a Vue component. 

Another workaround is to stick to some filenaming convention like "hello.component.js"  and configure the loader to include only "*. component.js" files.

**Comment by ktsn** [comment]
Hmm, I think detecting a component is impossible because a component can be any plain object. That likely cause false positive and true negative.

I'd rather decide directory/file name rules of component files to let the loader only be applied to components. It is clear enough for the users and they can control which files the loader should be used by themselves.

**Comment by Toilal** [comment]
I do agree. Let's close this pull request, but maybe the README should
follow this convention and explain why it's a good practice ?

**Comment by ktsn** [comment]
Yes, explaining about this in README is good idea.

**Comment by ktsn** [comment]
README is updated.
